### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SPM111** [joomplace/joomla-html5-flippingbook#1]
Hi,

Getting the error when installing zip package;

Install path does not exist.
Package Install: There was an error installing an extension: com_html5flippingbook_pro.zip

Tested on Joomla 3 and 4

Thanks Steve

**Comment by fsvblr** [comment]
Hi Steve.
This extension is for Joomla 3. For joomla 4 is not adapted.
How do you get a zip archive? Are you following the instructions at https://joomplace.com/github.html ?
Can you install other extensions on your site?
We have no problems installing our extensions on a Joomla 3 site.

**Comment by SPM111** [comment]
Hi Serguei

 

Thank you for replying, I had downloaded the zip file from github as attached .

 

I’ve tried on a local site and a published test site both using joomla 3  using the extension installer , not manual method.

 

Regards 

 


Stephen Morin

Sales at Allied Images Ltd

 

 

Office:     +44 (0)1604 670679

E-mail:    ***@***.*** ***@***.***>  

Address:  Allied Images, Unit 6 Station Works, Station Road, Long Buckby, Northants. NN6 7PF, UK

Website:   www.allied-images.com <http://www.allied-images.com/> 

Specialist Scanner and Software Solutions Distributor.

 

 

 

Contex - Large Format Scanners and MFP Solutions

Kurabo - Large A1 & A0 Flatbed Scanner

M-Files Online- innovative electronic information management system (EDMS) NEW from Allied Images.

Atiz - Scanners  for Books, Newspaper, Bound Documents upto A2

ST Imaging – ViewScan 4 Microfilm scanners

Elarscan – Planetary Style A2 & A1 Overhead Scanners

 

Disclaimer Notice::  <http://www.allied-images.com/images/OtherPDFs/EmailDisclaimer.pdf> Click here for email disclaimer details.

**Comment by fsvblr** [comment]
Hi Steve.
Sorry, I did not understand, where did you get the installation archive?
I hope you didn't use the green button "Code"->"Download ZIP" for this (the file name is "joomla-html5-flippingbook-2.2.zip").
And you used the releases page https://github.com/joomplace/joomla-html5-flippingbook/releases - the file name is "pkg_html5flippingbook_pro_2.2.7.zip". Instruction - https://joomplace.com/github.html .

**Comment by SPM111** [comment]
Hi Serguei,

 

Ah that’s it, I had downloaded using the Green button ‘Code’ !,  I’ve now tried with 2.2.7 from your link and it works 😊, so thank you

 

Will you update it for joomla 4,  I did try and got an error 

 

Regards 

 

Steve M

**Comment by fsvblr** [comment]
We do not plan to update our extensions for Joomla 4. Except as part of custom development (individual order).

I'm glad I could help you.
